export type PhotoView = "front" | "side";

export type Hotspot = {
  partId: string;
  view: PhotoView;
  left: number;
  top: number;
  width: number;
  height: number;
  label: string;
  featured?: boolean;
  category?: "hose" | "clamp" | "fastener" | "assembly";
};

export const HOTSPOTS: Hotspot[] = [
  // ===================== FRONT VIEW HOTSPOTS =====================
  {
    partId: "racor",
    view: "front",
    left: 7,
    top: 16,
    width: 18,
    height: 26,
    label: "Racor R15T",
    category: "assembly",
  },
  {
    partId: "coolant-bottle",
    view: "front",
    left: 20,
    top: 36,
    width: 12,
    height: 16,
    label: "Coolant Bottle",
    category: "assembly",
  },
  {
    partId: "return-hose",
    view: "front",
    left: 38,
    top: 44,
    width: 16,
    height: 14,
    label: "036868 Return Hose",
    featured: true,
    category: "hose",
  },
  {
    partId: "clamp-1",
    view: "front",
    left: 48,
    top: 38,
    width: 8,
    height: 7,
    label: "037163 Keystone Clamp",
    featured: true,
    category: "clamp",
  },
  {
    partId: "clamp-2",
    view: "front",
    left: 40,
    top: 52,
    width: 8,
    height: 7,
    label: "037163 Keystone Clamp",
    featured: true,
    category: "clamp",
  },
  {
    partId: "injection-pump",
    view: "front",
    left: 54,
    top: 40,
    width: 13,
    height: 14,
    label: "Inj. Pump 037103",
    category: "assembly",
  },
  {
    partId: "banjo-return-stack",
    view: "front",
    left: 52,
    top: 50,
    width: 8,
    height: 7,
    label: "037105 Banjo Washers",
    category: "fastener",
  },
  {
    partId: "hp-line-2",
    view: "front",
    left: 60,
    top: 28,
    width: 18,
    height: 16,
    label: "HP Lines 036951/52",
    category: "hose",
  },
  {
    partId: "injector-nuts",
    view: "front",
    left: 68,
    top: 24,
    width: 9,
    height: 8,
    label: "036921 Injector Nuts",
    category: "fastener",
  },
  {
    partId: "throttle",
    view: "front",
    left: 46,
    top: 58,
    width: 12,
    height: 10,
    label: "Throttle Linkage",
    category: "assembly",
  },
  {
    partId: "alternator",
    view: "front",
    left: 32,
    top: 62,
    width: 14,
    height: 12,
    label: "Alternator 037170",
    category: "assembly",
  },
  {
    partId: "manifold",
    view: "front",
    left: 42,
    top: 22,
    width: 16,
    height: 12,
    label: "Manifold 037120",
    category: "assembly",
  },
  {
    partId: "valve-cover-bolts",
    view: "front",
    left: 56,
    top: 16,
    width: 9,
    height: 8,
    label: "M6 Valve Cover Bolts",
    category: "fastener",
  },

  // ===================== SIDE VIEW HOTSPOTS =====================
  {
    partId: "wet-exhaust",
    view: "side",
    left: 58,
    top: 52,
    width: 28,
    height: 22,
    label: "Wet Exhaust Elbow",
    category: "assembly",
  },
  {
    partId: "manifold",
    view: "side",
    left: 28,
    top: 34,
    width: 20,
    height: 16,
    label: "Manifold 037120",
    category: "assembly",
  },
  {
    partId: "manifold-nuts",
    view: "side",
    left: 34,
    top: 30,
    width: 10,
    height: 8,
    label: "M8 Nuts & Washers",
    category: "fastener",
  },
  {
    partId: "heat-exchanger",
    view: "side",
    left: 22,
    top: 18,
    width: 22,
    height: 14,
    label: "Heat Exchanger 037130",
    category: "assembly",
  },
  {
    partId: "zinc-anode",
    view: "side",
    left: 26,
    top: 26,
    width: 8,
    height: 7,
    label: "011885 Zinc Anode",
    category: "fastener",
  },
  {
    partId: "hose-sea-to-heatex",
    view: "side",
    left: 14,
    top: 28,
    width: 12,
    height: 14,
    label: "037157 Sea Pump Hose",
    category: "hose",
  },
  {
    partId: "clamp-sea-pump",
    view: "side",
    left: 16,
    top: 38,
    width: 7,
    height: 6,
    label: "011405 (#16) Clamp",
    category: "clamp",
  },
  {
    partId: "transmission",
    view: "side",
    left: 8,
    top: 48,
    width: 16,
    height: 18,
    label: "Marine Gear ZF/Hurth",
    category: "assembly",
  },
  {
    partId: "hose-sump-drain",
    view: "side",
    left: 36,
    top: 70,
    width: 18,
    height: 12,
    label: "033691 Sump Drain Hose",
    category: "hose",
  },
  {
    partId: "banjo-sump-bolt",
    view: "side",
    left: 48,
    top: 74,
    width: 8,
    height: 7,
    label: "036819 Banjo Bolt",
    category: "fastener",
  },
];
