export type PartGroup =
  | "structure"
  | "fuel"
  | "cooling"
  | "electrical"
  | "lubrication"
  | "internals"
  | "drive"
  | "controls"
  | "fastener"
  | "hose"
  | "clamp";

export type EnginePart = {
  id: string;
  name: string;
  short: string;
  partNumber: string;
  qty: string;
  group: PartGroup;
  notes: string;
  models: string;
  highlight?: boolean;
  rest: [number, number, number];
  explode: [number, number, number];
  cutaway?: boolean;
  service?: string;
  category?: "hose" | "clamp" | "fastener" | "assembly" | "internal";
};

export const GROUP_LABEL: Record<PartGroup, string> = {
  structure: "Structure",
  fuel: "Fuel System (Port)",
  cooling: "Cooling & Exhaust (Starboard)",
  electrical: "Electrical",
  lubrication: "Lubrication",
  internals: "Running Gear",
  drive: "Drive & Gearbox",
  controls: "Controls & Linkage",
  fastener: "Nuts, Washers & Studs",
  hose: "Hoses & Lines",
  clamp: "Hose Clamps",
};

export const PARTS: EnginePart[] = [
  // ===================== STRUCTURE & CASING =====================
  {
    id: "block",
    name: "Cylinder block",
    short: "Engine block",
    partNumber: "037115-BLK",
    qty: "1",
    group: "structure",
    models: "20B TWO / 30B THREE",
    notes:
      "Cast iron block (Mitsubishi L2E/L3E base), 3 inline bores on the 30B THREE (2 on the 20B). Westerbeke marine engines wear the classic red finish. Port side houses injection pump and fuel system; Starboard side houses exhaust manifold and heat exchanger.",
    rest: [0, 0, 0],
    explode: [0, 0, 0],
    cutaway: true,
    category: "assembly",
  },
  {
    id: "head",
    name: "Cylinder head assembly",
    short: "Cylinder head",
    partNumber: "036901",
    qty: "1",
    group: "structure",
    models: "20B / 30B",
    notes:
      "Precision machined head housing the valves, injector pre-combustion chambers, and glow plugs. Torque head bolts in 3 staged passes in published spiral sequence after head gasket replacement.",
    rest: [0, 0.38, 0],
    explode: [0, 0.65, 0],
    cutaway: true,
    service: "Torque M10 head bolts to 54-61 lb-ft (73.5-83.4 N·m) in stages. Never overtighten cold without a torque wrench.",
    category: "assembly",
  },
  {
    id: "valve-cover",
    name: "Valve rocker cover",
    short: "Valve cover",
    partNumber: "036904",
    qty: "1",
    group: "structure",
    models: "20B / 30B",
    notes:
      "Top stamped rocker cover with oil filler opening and crankcase breather boss. Protects the rocker arms and valve springs. First item removed when setting valve lash or pulling injectors.",
    rest: [0, 0.55, 0],
    explode: [0, 0.95, 0],
    cutaway: true,
    service: "Replace cork/rubber perimeter gasket if weeping oil onto exhaust manifold.",
    category: "assembly",
  },
  {
    id: "oil-pan",
    name: "Oil sump pan",
    short: "Oil pan",
    partNumber: "036908",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes:
      "Cast/stamped lower oil sump with threaded banjo port for remote drain hose. Holds 3.0 to 3.8 quarts of 15W-40 marine diesel lube oil.",
    rest: [0, -0.38, 0],
    explode: [0, -0.72, 0],
    cutaway: true,
    service: "Inspect oil drain crush washers (036493 ×2) whenever servicing the sump line.",
    category: "assembly",
  },

  // ===================== STARBOARD COOLING & EXHAUST (X > 0) =====================
  {
    id: "manifold",
    name: "Exhaust manifold (freshwater cooled)",
    short: "Exhaust manifold",
    partNumber: "037120",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes:
      "Water-jacketed exhaust manifold mounted on the Starboard side of the cylinder head. Integrates freshwater cooling to lower engine compartment temperatures. The engine serial plate is mounted on this casting.",
    rest: [0.46, 0.38, 0],
    explode: [0.85, 0.2, 0],
    service: "Inspect cooling passages for scale buildup if the engine overheats under cruising load. Torque nuts to 18-21 lb-ft.",
    category: "assembly",
  },
  {
    id: "wet-exhaust",
    name: "Wet exhaust mixing elbow",
    short: "Mixing elbow",
    partNumber: "037124",
    qty: "1",
    group: "cooling",
    models: "Marine",
    notes:
      "Aft starboard mixing elbow: injected seawater mixes with hot exhaust gases to cool the exhaust down before exiting through the waterlock muffler.",
    rest: [0.55, 0.22, -0.56],
    explode: [0.95, -0.1, -0.65],
    service: "Pull elbow annually to inspect for carbon encrustation and saltwater corrosion.",
    category: "assembly",
  },
  {
    id: "thermostat-housing",
    name: "Thermostat housing & cover",
    short: "Thermostat",
    partNumber: "037380",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes:
      "Mounted on forward starboard cylinder head. Houses the 180°F (82°C) cooling thermostat regulating coolant circulation.",
    rest: [0.36, 0.50, 0.42],
    explode: [0.65, 0.75, 0.55],
    service: "Test thermostat in a pot of hot water with a thermometer if running too cool or overheating.",
    category: "assembly",
  },
  {
    id: "heat-exchanger",
    name: "Tubular heat exchanger assembly",
    short: "Heat exchanger",
    partNumber: "037130",
    qty: "1",
    group: "cooling",
    models: "Marine 20B/30B",
    notes:
      "Fore-and-aft tubular cupronickel heat exchanger mounted on the Starboard side directly above the exhaust manifold. Seawater flows through internal tubes while engine freshwater circulates across outer shell.",
    rest: [0.46, 0.62, 0.05],
    explode: [0.85, 0.95, 0.05],
    service: "Inspect sacrificial zinc anode (011885) monthly. Replace when 50% eroded.",
    category: "assembly",
  },
  {
    id: "zinc-anode",
    name: "Sacrificial zinc anode plug (pencil zinc)",
    short: "Zinc anode 011885",
    partNumber: "011885",
    qty: "1",
    group: "cooling",
    models: "All marine",
    notes: "1/4\" NPT brass plug with sacrificial zinc rod threaded into heat exchanger bottom.",
    rest: [0.46, 0.54, -0.25],
    explode: [0.85, 0.45, -0.45],
    category: "assembly",
  },

  // ===================== PORT FUEL SYSTEM (X < 0) =====================
  {
    id: "injection-pump",
    name: "Fuel injection pump assembly",
    short: "Injection pump",
    partNumber: "037102 (20B) / 037103 (30B)",
    qty: "1",
    group: "fuel",
    models: "037102 = 20B TWO; 037103 = 30B THREE",
    notes:
      "Bosch-type mechanical inline injection pump flange-mounted on the Port side crankcase shelf. Generates timed, metered high-pressure fuel pulses to each injector.",
    rest: [-0.30, 0.08, 0.04],
    explode: [-0.75, 0.08, 0.08],
    service: "Injection timing is shim-adjusted to ±1° BTDC (17°-19° BTDC).",
    category: "assembly",
  },
  {
    id: "injector-1",
    name: "Diesel fuel injector (cyl 1)",
    short: "Injector 1 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Aft cylinder injector on port head side. Pop pressure set to 1,920–2,060 PSI.",
    rest: [-0.20, 0.44, -0.24],
    explode: [-0.55, 0.75, -0.24],
    category: "assembly",
  },
  {
    id: "injector-2",
    name: "Diesel fuel injector (cyl 2)",
    short: "Injector 2 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Center cylinder injector on port head side.",
    rest: [-0.20, 0.44, 0.04],
    explode: [-0.55, 0.78, 0.04],
    category: "assembly",
  },
  {
    id: "injector-3",
    name: "Diesel fuel injector (cyl 3)",
    short: "Injector 3 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "30B THREE",
    notes: "Forward cylinder injector on port head side.",
    rest: [-0.20, 0.44, 0.24],
    explode: [-0.55, 0.75, 0.24],
    category: "assembly",
  },
  {
    id: "return-hose",
    name: "Hose, injector return to pump (focus part)",
    short: "036868 Return hose",
    partNumber: "036868",
    qty: "1",
    group: "hose",
    models: "20B TWO / 30B THREE",
    highlight: true,
    notes:
      "Official Pub #037115 item 51. Flexible ~6-inch green diesel leak-off hose on the Port side returning bypass fuel from the injector rail back to the injection pump. Secured by two 037163 Keystone clamps.",
    rest: [0, 0, 0],
    explode: [-0.55, 0.4, 0],
    category: "hose",
  },
  {
    id: "fuel-return-hose-2",
    name: "Hose, fuel return line",
    short: "Fuel return 034857",
    partNumber: "034857",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Port side return line carrying excess diesel back toward the fuel tank circuit.",
    rest: [0, 0, 0],
    explode: [-0.5, 0.15, -0.2],
    category: "hose",
  },
  {
    id: "fuel-return-hose-3",
    name: "Hose, auxiliary fuel return",
    short: "Fuel return 037187",
    partNumber: "037187",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Auxiliary return hose section connecting the return banjo stack.",
    rest: [0, 0, 0],
    explode: [-0.45, 0.1, 0.2],
    category: "hose",
  },
  {
    id: "hp-line-1",
    name: "High-pressure injector steel line (cyl 1)",
    short: "HP line 1 (036951)",
    partNumber: "036951",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Rigid steel pipe delivering 2,000 PSI pulses from pump delivery valve 1 to injector 1.",
    rest: [0, 0, 0],
    explode: [-0.45, 0.35, -0.1],
    category: "hose",
  },
  {
    id: "hp-line-2",
    name: "High-pressure injector steel line (cyl 2)",
    short: "HP line 2 (036952)",
    partNumber: "036952",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Center rigid steel injection line to cylinder 2 injector.",
    rest: [0, 0, 0],
    explode: [-0.45, 0.35, 0],
    category: "hose",
  },
  {
    id: "hp-line-3",
    name: "High-pressure injector steel line (cyl 3)",
    short: "HP line 3 (036953)",
    partNumber: "036953",
    qty: "1",
    group: "hose",
    models: "30B THREE",
    notes: "Forward rigid steel injection line to cylinder 3 injector.",
    rest: [0, 0, 0],
    explode: [-0.45, 0.35, 0.1],
    category: "hose",
  },
  {
    id: "leak-off-rail",
    name: "Line, injector leak-off bridge rail",
    short: "Leak-off rail 037098",
    partNumber: "037098",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Rigid metal bridge rail spanning injectors on the port side collecting leak-off.",
    rest: [-0.21, 0.52, 0.04],
    explode: [-0.55, 0.85, 0.04],
    category: "hose",
  },
  {
    id: "racor",
    name: "Primary fuel filter / water separator (aftermarket)",
    short: "Racor R15T / 500FG",
    partNumber: "Racor R15T / R15S",
    qty: "1",
    group: "fuel",
    models: "Bulkhead mounted",
    notes: "Port bulkhead 10-micron fuel filter / water separator with clear sediment bowl and drain.",
    rest: [-0.48, 0.30, 0.36],
    explode: [-0.98, 0.42, 0.48],
    category: "assembly",
  },
  {
    id: "stock-filter",
    name: "Stock secondary fuel filter assembly",
    short: "Secondary filter 030210",
    partNumber: "030210",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Port-mounted secondary 2-micron fine filter.",
    rest: [-0.44, 0.18, -0.22],
    explode: [-0.92, 0.22, -0.26],
    category: "assembly",
  },
  {
    id: "lift-pump",
    name: "Fuel lift pump 12V DC",
    short: "Lift pump 039275",
    partNumber: "039275",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Solid-state 12V pulse fuel pump on port engine bracket.",
    rest: [-0.44, -0.06, 0.36],
    explode: [-0.90, -0.18, 0.48],
    category: "assembly",
  },
  {
    id: "hose-fuel-supply",
    name: "Hose, fuel supply (tank to Racor)",
    short: "Hose 030025",
    partNumber: "030025",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Port fuel supply line from tank to Racor filter.",
    rest: [0, 0, 0],
    explode: [-0.6, 0.2, 0.4],
    category: "hose",
  },
  {
    id: "hose-lift-to-filter",
    name: "Hose, lift pump to fuel filter",
    short: "Hose 038047",
    partNumber: "038047",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Port fuel hose connecting lift pump to secondary filter.",
    rest: [0, 0, 0],
    explode: [-0.55, 0.1, 0.1],
    category: "hose",
  },
  {
    id: "hose-filter-to-inj",
    name: "Hose, filter to injection pump",
    short: "Hose 036865",
    partNumber: "036865",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Clean fuel line connecting secondary filter to injection pump inlet.",
    rest: [0, 0, 0],
    explode: [-0.5, 0.15, -0.1],
    category: "hose",
  },
  {
    id: "glow-plugs",
    name: "Glow plugs & busbar harness",
    short: "Glow plugs 036930",
    partNumber: "036930",
    qty: "3",
    group: "electrical",
    models: "20B / 30B",
    notes: "Electric pre-heat elements on port cylinder head.",
    rest: [-0.18, 0.38, 0.02],
    explode: [-0.48, 0.68, 0.02],
    category: "assembly",
  },
  {
    id: "throttle",
    name: "Throttle speed control lever & governor linkage",
    short: "Throttle linkage",
    partNumber: "037195",
    qty: "1",
    group: "controls",
    models: "20B / 30B",
    notes: "Port speed control governor ball-joint linkage rod.",
    rest: [-0.46, 0.26, 0.22],
    explode: [-0.82, 0.44, 0.35],
    category: "assembly",
  },

  // ===================== FRONT TIMING CASE & ELECTRICAL (STARBOARD/PORT FRONT) =====================
  {
    id: "raw-water-pump",
    name: "Raw-water seawater pump",
    short: "Sea pump 037140",
    partNumber: "037140",
    qty: "1",
    group: "cooling",
    models: "Marine",
    notes: "Gear-driven bronze seawater pump mounted on the Port lower front timing case.",
    rest: [-0.26, -0.06, 0.70],
    explode: [-0.45, -0.05, 1.15],
    category: "assembly",
  },
  {
    id: "freshwater-pump",
    name: "Freshwater circulating water pump",
    short: "Circulating pump",
    partNumber: "037145",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes: "Centrifugal coolant pump on upper front timing case.",
    rest: [0.06, 0.30, 0.66],
    explode: [0.15, 0.45, 1.05],
    category: "assembly",
  },
  {
    id: "alternator",
    name: "Marine 12V 55A alternator",
    short: "Alternator 037170",
    partNumber: "037170",
    qty: "1",
    group: "electrical",
    models: "12V marine isolated ground",
    notes: "Mounted on the Starboard front cylinder head bracket.",
    rest: [-0.44, 0.16, 0.62],
    explode: [-0.92, 0.14, 0.88],
    category: "assembly",
  },
  {
    id: "alt-bracket",
    name: "Alternator mounting & adjusting arm bracket",
    short: "Alt bracket 037172",
    partNumber: "037172",
    qty: "1",
    group: "electrical",
    models: "20B / 30B",
    notes: "Bracket bolting alternator to cylinder head.",
    rest: [-0.38, 0.18, 0.52],
    explode: [-0.78, 0.24, 0.75],
    category: "assembly",
  },
  {
    id: "starter",
    name: "12V reduction gear starter motor",
    short: "Starter motor 037180",
    partNumber: "037180",
    qty: "1",
    group: "electrical",
    models: "12V 1.2kW",
    notes: "High-torque starter mounted on Starboard aft flywheel housing.",
    rest: [0.40, -0.08, -0.52],
    explode: [0.92, -0.14, -0.56],
    category: "assembly",
  },
  {
    id: "pulley",
    name: "Crankshaft damper drive pulley",
    short: "Crank pulley",
    partNumber: "036912",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Harmonic drive pulley on front crankshaft snout.",
    rest: [0, 0.02, 0.72],
    explode: [0, 0, 1.15],
    category: "assembly",
  },
  {
    id: "belt",
    name: "V-belt drive (crank to pump & alternator)",
    short: "Drive belt 037168",
    partNumber: "037168",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "3-point closed triangle marine V-belt.",
    rest: [0, 0, 0],
    explode: [0, 0.15, 1.15],
    category: "assembly",
  },
  {
    id: "coolant-bottle",
    name: "Translucent coolant recovery expansion bottle",
    short: "Coolant bottle",
    partNumber: "030040",
    qty: "1",
    group: "cooling",
    models: "All",
    notes: "Translucent coolant recovery tank on port bulkhead.",
    rest: [-0.56, 0.16, 0.52],
    explode: [-0.95, 0.02, 0.65],
    category: "assembly",
  },

  // ===================== COOLING HOSES =====================
  {
    id: "hose-sea-to-heatex",
    name: "Hose, raw-water pump to heat exchanger",
    short: "Hose 037157",
    partNumber: "037157",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Seawater hose from raw water pump outlet up to heat exchanger.",
    rest: [0, 0, 0],
    explode: [-0.25, 0.5, 0.5],
    category: "hose",
  },
  {
    id: "hose-thermostat-manifold",
    name: "Hose, thermostat to exhaust manifold",
    short: "Hose 037383",
    partNumber: "037383",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Coolant hose from thermostat to exhaust manifold.",
    rest: [0, 0, 0],
    explode: [0.5, 0.4, 0.2],
    category: "hose",
  },
  {
    id: "hose-fw-to-heatex",
    name: "Hose, freshwater circulating pump to heat exchanger",
    short: "Hose 037506",
    partNumber: "037506",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Closed-loop coolant hose from exchanger to water pump.",
    rest: [0, 0, 0],
    explode: [0.15, 0.6, 0.35],
    category: "hose",
  },
  {
    id: "hose-flow-ctrl-1",
    name: "Hose, flow control bypass line",
    short: "Hose 036654",
    partNumber: "036654",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Starboard bypass balance hose.",
    rest: [0, 0, 0],
    explode: [0.35, 0.3, 0.4],
    category: "hose",
  },
  {
    id: "hose-flow-ctrl-2",
    name: "Hose, flow control return line",
    short: "Hose 036556",
    partNumber: "036556",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Starboard balance line.",
    rest: [0, 0, 0],
    explode: [0.35, 0.25, 0.35],
    category: "hose",
  },
  {
    id: "hose-sump-drain",
    name: "Hose, oil sump drain line",
    short: "Sump hose 033691",
    partNumber: "033691",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Remote oil drain hose from oil pan.",
    rest: [0, 0, 0],
    explode: [-0.4, -0.3, 0.2],
    category: "hose",
  },
  {
    id: "hose-trans-cooler-1",
    name: "Hose, transmission oil cooler supply",
    short: "Trans hose 037154 (1)",
    partNumber: "037154",
    qty: "1",
    group: "hose",
    models: "Marine gear",
    notes: "Seawater cooling supply line to transmission cooler.",
    rest: [0, 0, 0],
    explode: [0.35, -0.15, -0.5],
    category: "hose",
  },
  {
    id: "hose-trans-cooler-2",
    name: "Hose, transmission oil cooler return",
    short: "Trans hose 037154 (2)",
    partNumber: "037154",
    qty: "1",
    group: "hose",
    models: "Marine gear",
    notes: "Discharge from transmission cooler to wet exhaust mixing elbow.",
    rest: [0, 0, 0],
    explode: [0.45, -0.1, -0.45],
    category: "hose",
  },
  {
    id: "hose-coolant-overflow",
    name: "Hose, coolant recovery overflow",
    short: "Overflow tube",
    partNumber: "030030",
    qty: "1",
    group: "hose",
    models: "All",
    notes: "Clear tubing from heat exchanger neck to coolant bottle.",
    rest: [0, 0, 0],
    explode: [-0.5, 0.4, 0.4],
    category: "hose",
  },

  // ===================== FASTENERS & CLAMPS =====================
  {
    id: "clamp-1",
    name: "Keystone clamp (injector return hose top)",
    short: "Keystone clamp 037163",
    partNumber: "037163",
    qty: "1",
    group: "clamp",
    models: "20B / 30B",
    highlight: true,
    notes: "0.420\" Keystone clamp clamping 036868 return hose to injector rail.",
    rest: [-0.26, 0.56, -0.24],
    explode: [-0.55, 0.78, -0.24],
    category: "clamp",
  },
  {
    id: "clamp-2",
    name: "Keystone clamp (injector return hose bottom)",
    short: "Keystone clamp 037163",
    partNumber: "037163",
    qty: "1",
    group: "clamp",
    models: "20B / 30B",
    highlight: true,
    notes: "Second 037163 Keystone clamp securing green return hose to pump return barb.",
    rest: [-0.44, 0.16, 0.08],
    explode: [-0.85, 0.32, 0.12],
    category: "clamp",
  },
  {
    id: "clamp-sea-pump",
    name: "Hose clamp size 16 (sea pump outlet)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless clamp on sea pump outlet hose.",
    rest: [-0.26, 0.01, 0.72],
    explode: [-0.38, 0.25, 0.95],
    category: "clamp",
  },
  {
    id: "clamp-thermo-1",
    name: "Hose clamp size 16 (thermostat cover)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless clamp on thermostat neck.",
    rest: [0.36, 0.52, 0.40],
    explode: [0.62, 0.75, 0.48],
    category: "clamp",
  },
  {
    id: "clamp-thermo-2",
    name: "Hose clamp size 16 (manifold inlet)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless clamp on exhaust manifold inlet.",
    rest: [0.46, 0.42, 0.18],
    explode: [0.85, 0.6, 0.22],
    category: "clamp",
  },
  {
    id: "clamp-fw-pump",
    name: "Hose clamp size 16 (freshwater pump)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Secures hose to circulating pump.",
    rest: [0.06, 0.26, 0.66],
    explode: [0.15, 0.65, 0.95],
    category: "clamp",
  },
  {
    id: "clamp-exchanger-in",
    name: "Hose clamp size 20 (heat exchanger port)",
    short: "Clamp 021878 (#20)",
    partNumber: "021878",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Clamp at heat exchanger raw water inlet.",
    rest: [-0.26, 0.72, 0.22],
    explode: [-0.4, 0.95, 0.4],
    category: "clamp",
  },
  {
    id: "clamp-small-cooling",
    name: "Hose clamp size 12 (bypass cooling)",
    short: "Clamp 011386 (#12)",
    partNumber: "011386",
    qty: "2",
    group: "clamp",
    models: "All",
    notes: "Bypass hose clamps.",
    rest: [0.28, 0.34, 0.46],
    explode: [0.45, 0.55, 0.65],
    category: "clamp",
  },
  {
    id: "clamp-fuel-mini",
    name: "Hose clamp mini fuel line",
    short: "Clamp 024906 (Fuel)",
    partNumber: "024906",
    qty: "4",
    group: "clamp",
    models: "All",
    notes: "Mini fuel clamps.",
    rest: [-0.50, -0.06, 0.36],
    explode: [-0.95, 0.12, 0.45],
    category: "clamp",
  },
  {
    id: "manifold-studs",
    name: "Studs M8×25 (exhaust manifold to head)",
    short: "M8×25 Studs 015830",
    partNumber: "015830",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "High-tensile studs threaded into cylinder head exhaust ports.",
    rest: [0.40, 0.38, 0],
    explode: [0.65, 0.2, 0],
    category: "fastener",
  },
  {
    id: "manifold-washers",
    name: "Washers M8 (flat + spring lock)",
    short: "M8 Washers 031787/786",
    partNumber: "031787 / 031786",
    qty: "12",
    group: "fastener",
    models: "20B / 30B",
    notes: "Washers under manifold nuts.",
    rest: [0.49, 0.38, 0],
    explode: [0.95, 0.2, 0],
    category: "fastener",
  },
  {
    id: "manifold-nuts",
    name: "Nuts M8 (manifold hold-down)",
    short: "M8 Nuts 018242",
    partNumber: "018242",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hold-down nuts for exhaust manifold.",
    rest: [0.52, 0.38, 0],
    explode: [1.05, 0.2, 0],
    category: "fastener",
  },
  {
    id: "valve-cover-bolts",
    name: "Capscrews M6 with M6 flat & lock washers",
    short: "M6 Bolts 018804",
    partNumber: "018804 / 031784",
    qty: "4",
    group: "fastener",
    models: "20B / 30B",
    notes: "Capscrews securing the valve cover.",
    rest: [0, 0.55, 0],
    explode: [0, 1.15, 0],
    category: "fastener",
  },
  {
    id: "banjo-return-stack",
    name: "Washers, banjo crush copper (fuel return stack)",
    short: "Banjo washer 037105 ×2",
    partNumber: "037105",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    highlight: true,
    notes: "Copper crush washers on the fuel-return banjo fitting.",
    rest: [-0.44, 0.16, 0.08],
    explode: [-0.82, 0.25, 0.14],
    category: "fastener",
  },
  {
    id: "banjo-bleed-stack",
    name: "Washer, banjo crush (fuel bleed stack)",
    short: "Bleed washer 037104",
    partNumber: "037104",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "Copper washer on injection pump air bleed screw.",
    rest: [-0.44, 0.24, 0.04],
    explode: [-0.88, 0.35, 0.08],
    category: "fastener",
  },
  {
    id: "banjo-bolt-bleed",
    name: "Banjo bolt, air bleed valve",
    short: "Bleed bolt 037110",
    partNumber: "037110",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hollow banjo bolt used to bleed air from pump gallery.",
    rest: [-0.44, 0.26, 0.04],
    explode: [-0.95, 0.4, 0.08],
    category: "fastener",
  },
  {
    id: "banjo-bolt-fuel",
    name: "Banjo bolt, fuel pump inlet/return",
    short: "Banjo bolt 037111",
    partNumber: "037111",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hollow bolt with metering orifice for pump supply.",
    rest: [-0.46, 0.06, -0.04],
    explode: [-0.92, 0.15, -0.06],
    category: "fastener",
  },
  {
    id: "banjo-washer-m8",
    name: "Banjo crush washer M8",
    short: "M8 Banjo washer 030289",
    partNumber: "030289",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "M8 copper sealing ring.",
    rest: [-0.42, 0.12, 0.14],
    explode: [-0.82, 0.2, 0.2],
    category: "fastener",
  },
  {
    id: "banjo-washer-m14",
    name: "Banjo crush washer M14",
    short: "M14 Banjo washer 030291",
    partNumber: "030291",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "M14 copper sealing ring.",
    rest: [-0.46, 0.06, -0.04],
    explode: [-0.88, 0.14, -0.05],
    category: "fastener",
  },
  {
    id: "banjo-cooling-m16",
    name: "Banjo washer M16 (cooling circuit)",
    short: "M16 Banjo washer 037162",
    partNumber: "037162",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "M16 copper sealing washer.",
    rest: [0.34, 0.44, 0.38],
    explode: [0.65, 0.7, 0.52],
    category: "fastener",
  },
  {
    id: "banjo-sump-washers",
    name: "Banjo crush washers ×2 (oil sump drain)",
    short: "Sump washer 036493 ×2",
    partNumber: "036493",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "Copper crush washers on oil sump banjo.",
    rest: [-0.28, -0.38, 0.1],
    explode: [-0.55, -0.65, 0.18],
    category: "fastener",
  },
  {
    id: "banjo-sump-bolt",
    name: "Banjo bolt (oil sump drain valve)",
    short: "Sump banjo bolt 036819",
    partNumber: "036819",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hollow banjo bolt securing oil drain hose.",
    rest: [-0.28, -0.38, 0.1],
    explode: [-0.65, -0.65, 0.18],
    category: "fastener",
  },
  {
    id: "injector-nuts",
    name: "Nuts, injector high-pressure line flare & hold-down",
    short: "Injector nuts 036921",
    partNumber: "036921",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hardened flare tube nuts on injector lines.",
    rest: [-0.25, 0.52, 0.04],
    explode: [-0.6, 0.88, 0.04],
    category: "fastener",
  },
  {
    id: "injector-gaskets",
    name: "Gaskets, injector nozzle copper heat shields",
    short: "Injector gaskets 036922",
    partNumber: "036922",
    qty: "3",
    group: "fastener",
    models: "20B / 30B",
    notes: "Copper heat-shield washers under injectors.",
    rest: [-0.25, 0.44, 0.04],
    explode: [-0.5, 0.65, 0.04],
    category: "fastener",
  },
  {
    id: "engine-mount-nuts",
    name: "Nuts M12 self-locking (vibration isolator mounts)",
    short: "M12 Locknut 037353",
    partNumber: "037353",
    qty: "4",
    group: "fastener",
    models: "All",
    notes: "Nylon-insert self-locking nuts on motor mount feet.",
    rest: [0, -0.22, 0],
    explode: [0, -0.5, 0],
    category: "fastener",
  },
  {
    id: "alt-adjust-bolt",
    name: "Alternator adjuster bolt M10",
    short: "M10 Bolt 015887",
    partNumber: "015887",
    qty: "1",
    group: "fastener",
    models: "All",
    notes: "Slotted arm adjustment bolt.",
    rest: [-0.44, 0.26, 0.60],
    explode: [-0.88, 0.36, 0.82],
    category: "fastener",
  },

  // ===================== DRIVE, TRANSMISSION, SHAFT & PROPELLER =====================
  {
    id: "flywheel-housing",
    name: "Flywheel bell housing",
    short: "Bell housing",
    partNumber: "037185",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Cast aluminum bell housing enclosing flywheel and damper plate.",
    rest: [0, -0.02, -0.66],
    explode: [0, 0, -0.55],
    cutaway: true,
    category: "assembly",
  },
  {
    id: "flywheel",
    name: "Flywheel & starter ring gear",
    short: "Flywheel",
    partNumber: "036915",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Heavy cast iron flywheel with starter ring gear.",
    rest: [0, -0.02, -0.66],
    explode: [0, 0, -1.05],
    category: "assembly",
  },
  {
    id: "transmission",
    name: "Marine transmission gearbox (Hurth / ZF)",
    short: "Transmission (ZF/Hurth)",
    partNumber: "HBW-50 / ZF10M",
    qty: "1",
    group: "drive",
    models: "Mechanical marine gear",
    notes: "Helical-gear marine reduction gearbox with forward adapter ring bolted flush to bell housing.",
    rest: [0, -0.04, -0.98],
    explode: [0, -0.1, -1.65],
    category: "assembly",
  },
  {
    id: "trans-cooler",
    name: "Transmission oil heat exchanger cooler",
    short: "Trans cooler 037150",
    partNumber: "037150",
    qty: "1",
    group: "drive",
    models: "Marine",
    notes: "In-line tube oil cooler mounted on starboard bracket.",
    rest: [0.34, -0.04, -0.92],
    explode: [0.65, -0.08, -1.35],
    category: "assembly",
  },
  {
    id: "shift-linkage",
    name: "Transmission shift lever & cable bracket",
    short: "Shift lever",
    partNumber: "037190",
    qty: "1",
    group: "controls",
    models: "All",
    notes: "External shift lever mounted on selector pivot boss.",
    rest: [0.18, 0.10, -0.95],
    explode: [0.60, 0.20, -1.45],
    category: "assembly",
  },
  {
    id: "driveshaft-coupling",
    name: "Flexible shaft coupling & isolator disc",
    short: "Shaft coupling 037360",
    partNumber: "037360",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "Polyurethane flexible vibration damping disc.",
    rest: [0, -0.04, -1.24],
    explode: [0, -0.1, -1.80],
    category: "assembly",
  },
  {
    id: "shaft-coupling-hub",
    name: "Split shaft coupling hub with clamp bolts",
    short: "Coupling hub 037362",
    partNumber: "037362",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "Machined steel split coupling locking onto driveshaft.",
    rest: [0, -0.04, -1.32],
    explode: [0, -0.1, -2.00],
    category: "assembly",
  },
  {
    id: "prop-driveshaft",
    name: "Stainless steel propeller driveshaft (1\" Aquamet)",
    short: "Driveshaft 037365",
    partNumber: "037365",
    qty: "1",
    group: "drive",
    models: "1\" Aquamet 17/22",
    notes: "Precision ground marine stainless steel propeller shaft.",
    rest: [0, -0.04, -1.75],
    explode: [0, -0.1, -2.40],
    category: "assembly",
  },
  {
    id: "shaft-seal-stuffing",
    name: "Bronze marine stuffing box / shaft seal packing gland",
    short: "Shaft seal 037370",
    partNumber: "037370",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "Cast bronze stuffing box gland with packing nut and flax seals.",
    rest: [0, -0.04, -1.48],
    explode: [0, -0.1, -2.15],
    category: "assembly",
  },
  {
    id: "stern-tube-hose",
    name: "Heavy-duty stern tube hose with T-bolt clamps",
    short: "Stern hose 037372",
    partNumber: "037372",
    qty: "1",
    group: "hose",
    models: "Marine 1-3/4\" ID",
    notes: "5-ply wire-reinforced marine silicone/rubber hose with dual T-bolt clamps.",
    rest: [0, -0.04, -1.58],
    explode: [0, -0.1, -2.25],
    category: "hose",
  },
  {
    id: "shaft-zinc-anode",
    name: "Sacrificial zinc collar anode (shaft zinc)",
    short: "Shaft zinc 037378",
    partNumber: "037378",
    qty: "1",
    group: "drive",
    models: "1\" shaft",
    notes: "Split zinc collar clamped around propeller shaft.",
    rest: [0, -0.04, -1.88],
    explode: [0, -0.1, -2.55],
    category: "assembly",
  },
  {
    id: "propeller",
    name: "3-Blade bronze marine propeller (14RH10 cupped)",
    short: "Propeller 037385",
    partNumber: "037385",
    qty: "1",
    group: "drive",
    models: "14RH10 / 15RH11",
    notes: "Manganese bronze 3-blade cupped marine propeller with 3D hydrofoil helical blades.",
    rest: [0, -0.04, -2.10],
    explode: [0, -0.1, -2.85],
    category: "assembly",
  },
  {
    id: "prop-castle-nut",
    name: "Slotted brass castle nut, cotter pin & drive key",
    short: "Castle nut 037388",
    partNumber: "037388",
    qty: "1",
    group: "fastener",
    models: "Marine shaft",
    notes: "Slotted castle nut and cotter pin locking the propeller onto shaft taper.",
    rest: [0, -0.04, -2.18],
    explode: [0, -0.1, -3.00],
    category: "fastener",
  },

  // ===================== LUBRICATION & SERVICE =====================
  {
    id: "oil-filter",
    name: "Full-flow spin-on lube oil filter",
    short: "Oil filter 036918",
    partNumber: "036918",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "Spin-on oil filter mounted on port aft block rail.",
    rest: [-0.48, -0.14, -0.38],
    explode: [-0.90, -0.22, -0.45],
    category: "assembly",
  },
  {
    id: "oil-dipstick",
    name: "Oil dipstick & guide tube",
    short: "Dipstick 036925",
    partNumber: "036925",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "Graduated dipstick with yellow/red handle on port side.",
    rest: [-0.42, 0.1, -0.28],
    explode: [-0.85, 0.25, -0.38],
    category: "assembly",
  },
  {
    id: "oil-fill-cap",
    name: "Oil filler cap & O-ring seal",
    short: "Oil cap 036928",
    partNumber: "036928",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "Threaded oil filler cap on valve rocker cover.",
    rest: [0, 0.62, 0.38],
    explode: [0, 1.25, 0.38],
    category: "assembly",
  },

  // ===================== RUNNING GEAR INTERNALS =====================
  {
    id: "crankshaft",
    name: "Forged steel crankshaft",
    short: "Crankshaft",
    partNumber: "036935",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Forged steel crankshaft with integral counterweights.",
    rest: [0, -0.16, 0],
    explode: [0, -0.65, 0],
    category: "internal",
  },
  {
    id: "piston-1",
    name: "Piston & ring pack (cyl 1)",
    short: "Piston 1",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Aft cylinder piston.",
    rest: [0, 0.08, -0.24],
    explode: [0, 0.35, -0.45],
    category: "internal",
  },
  {
    id: "piston-2",
    name: "Piston & ring pack (cyl 2)",
    short: "Piston 2",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Center cylinder piston.",
    rest: [0, 0.08, 0.04],
    explode: [0, 0.4, 0.04],
    category: "internal",
  },
  {
    id: "piston-3",
    name: "Piston & ring pack (cyl 3)",
    short: "Piston 3",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "30B THREE",
    notes: "Forward cylinder piston.",
    rest: [0, 0.08, 0.24],
    explode: [0, 0.35, 0.45],
    category: "internal",
  },
  {
    id: "rod-1",
    name: "Connecting rod & bearing cap (cyl 1)",
    short: "Rod 1",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Aft connecting rod assembly.",
    rest: [0, -0.04, -0.24],
    explode: [0.15, -0.35, -0.45],
    category: "internal",
  },
  {
    id: "rod-2",
    name: "Connecting rod & bearing cap (cyl 2)",
    short: "Rod 2",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Center connecting rod assembly.",
    rest: [0, -0.04, 0.04],
    explode: [0.15, -0.4, 0.04],
    category: "internal",
  },
  {
    id: "rod-3",
    name: "Connecting rod & bearing cap (cyl 3)",
    short: "Rod 3",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "30B THREE",
    notes: "Forward connecting rod assembly.",
    rest: [0, -0.04, 0.24],
    explode: [0.15, -0.35, 0.45],
    category: "internal",
  },
  {
    id: "camshaft",
    name: "Camshaft & valve lifters",
    short: "Camshaft",
    partNumber: "036950",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Gear-driven camshaft operating intake/exhaust valves.",
    rest: [0, 0.22, 0],
    explode: [0, 0.55, 0],
    category: "internal",
  },
];

export const PARTS_BY_ID: Record<string, EnginePart> = Object.fromEntries(
  PARTS.map((p) => [p.id, p]),
);

export const STRIP_ORDER: string[] = [
  "belt",
  "pulley",
  "alternator",
  "alt-bracket",
  "alt-adjust-bolt",
  "coolant-bottle",
  "hose-coolant-overflow",
  "racor",
  "hose-fuel-supply",
  "clamp-1",
  "clamp-2",
  "return-hose",
  "fuel-return-hose-2",
  "fuel-return-hose-3",
  "clamp-fuel-mini",
  "hp-line-1",
  "hp-line-2",
  "hp-line-3",
  "leak-off-rail",
  "injector-nuts",
  "injector-gaskets",
  "injector-1",
  "injector-2",
  "injector-3",
  "glow-plugs",
  "throttle",
  "banjo-return-stack",
  "banjo-bleed-stack",
  "banjo-bolt-bleed",
  "banjo-bolt-fuel",
  "banjo-washer-m8",
  "banjo-washer-m14",
  "hose-filter-to-inj",
  "hose-lift-to-filter",
  "lift-pump",
  "stock-filter",
  "injection-pump",
  "clamp-sea-pump",
  "hose-sea-to-heatex",
  "clamp-thermo-1",
  "clamp-thermo-2",
  "hose-thermostat-manifold",
  "clamp-fw-pump",
  "hose-fw-to-heatex",
  "clamp-exchanger-in",
  "clamp-small-cooling",
  "hose-flow-ctrl-1",
  "hose-flow-ctrl-2",
  "zinc-anode",
  "heat-exchanger",
  "raw-water-pump",
  "freshwater-pump",
  "thermostat-housing",
  "wet-exhaust",
  "manifold-nuts",
  "manifold-washers",
  "manifold-studs",
  "manifold",
  "banjo-cooling-m16",
  "valve-cover-bolts",
  "oil-fill-cap",
  "valve-cover",
  "oil-filter",
  "oil-dipstick",
  "starter",
  "hose-sump-drain",
  "banjo-sump-washers",
  "banjo-sump-bolt",
  "engine-mount-nuts",
  "prop-castle-nut",
  "propeller",
  "shaft-zinc-anode",
  "shaft-seal-stuffing",
  "stern-tube-hose",
  "prop-driveshaft",
  "shaft-coupling-hub",
  "driveshaft-coupling",
  "shift-linkage",
  "hose-trans-cooler-1",
  "hose-trans-cooler-2",
  "trans-cooler",
  "transmission",
  "flywheel",
  "flywheel-housing",
  "head",
  "oil-pan",
  "camshaft",
  "piston-1",
  "piston-2",
  "piston-3",
  "rod-1",
  "rod-2",
  "rod-3",
  "crankshaft",
  "block",
];

export const MANUALS = [
  {
    label: "Parts list #037115",
    href: "https://www.westerbeke.com/parts%20manual/37115_rev2_12c_20b_30b_parts_list.pdf",
  },
  {
    label: "Tech manual #037600",
    href: "https://www.westerbeke.com/technical%20manual/37600_12c_20b_30b_technical_manual.pdf",
  },
  {
    label: "Westerbeke official",
    href: "https://www.westerbeke.com/",
  },
];
