export type PartGroup =
  | "structure"
  | "fuel"
  | "cooling"
  | "electrical"
  | "lubrication"
  | "internals"
  | "drive"
  | "controls"
  | "fastener"
  | "hose"
  | "clamp";

export type EnginePart = {
  id: string;
  name: string;
  short: string;
  partNumber: string;
  qty: string;
  group: PartGroup;
  notes: string;
  models: string;
  highlight?: boolean;
  rest: [number, number, number];
  explode: [number, number, number];
  cutaway?: boolean;
  service?: string;
  category?: "hose" | "clamp" | "fastener" | "assembly" | "internal";
};

export const GROUP_LABEL: Record<PartGroup, string> = {
  structure: "Structure",
  fuel: "Fuel System",
  cooling: "Cooling & Exhaust",
  electrical: "Electrical",
  lubrication: "Lubrication",
  internals: "Running Gear",
  drive: "Drive & Gearbox",
  controls: "Controls & Linkage",
  fastener: "Nuts, Washers & Studs",
  hose: "Hoses & Lines",
  clamp: "Hose Clamps",
};

export const PARTS: EnginePart[] = [
  // ===================== STRUCTURE & CASING =====================
  {
    id: "block",
    name: "Cylinder block",
    short: "Engine block",
    partNumber: "037115-BLK",
    qty: "1",
    group: "structure",
    models: "20B TWO / 30B THREE",
    notes:
      "Cast iron block, 3 inline bores on the 30B THREE (2 on the 20B). Westerbeke marine engines of this family wear the classic red finish. Salt air and heat cycles cause paint peeling. Always confirm serial plate before ordering internal overhaul parts.",
    rest: [0, 0, 0],
    explode: [0, 0, 0],
    cutaway: true,
    category: "assembly",
  },
  {
    id: "head",
    name: "Cylinder head assembly",
    short: "Cylinder head",
    partNumber: "036901",
    qty: "1",
    group: "structure",
    models: "20B / 30B",
    notes:
      "Precision machined head housing the valves, injector pre-combustion chambers, and glow plugs. Torque head bolts in 3 staged passes in published spiral sequence after head gasket replacement.",
    rest: [0, 0.38, 0],
    explode: [0, 0.65, 0],
    cutaway: true,
    service: "Torque M10 head bolts to 54-61 lb-ft (73.5-83.4 N·m) in stages. Never overtighten cold without a torque wrench.",
    category: "assembly",
  },
  {
    id: "valve-cover",
    name: "Valve rocker cover",
    short: "Valve cover",
    partNumber: "036904",
    qty: "1",
    group: "structure",
    models: "20B / 30B",
    notes:
      "Top stamped rocker cover with oil filler opening and crankcase breather boss. Protects the rocker arms and valve springs. First item removed when setting valve lash or pulling injectors.",
    rest: [0, 0.55, 0],
    explode: [0, 0.95, 0],
    cutaway: true,
    service: "Replace cork/rubber perimeter gasket if weeping oil onto exhaust manifold.",
    category: "assembly",
  },
  {
    id: "oil-pan",
    name: "Oil sump pan",
    short: "Oil pan",
    partNumber: "036908",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes:
      "Cast/stamped lower oil sump with threaded banjo port for remote drain hose. Holds 3.0 to 3.8 quarts of 15W-40 marine diesel lube oil.",
    rest: [0, -0.38, 0],
    explode: [0, -0.72, 0],
    cutaway: true,
    service: "Inspect oil drain crush washers (036493 ×2) whenever servicing the sump line.",
    category: "assembly",
  },
  {
    id: "manifold",
    name: "Exhaust manifold (freshwater cooled)",
    short: "Exhaust manifold",
    partNumber: "037120",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes:
      "Water-jacketed exhaust manifold painted marine red. Integrates freshwater cooling to lower engine compartment temperatures. The engine serial plate is mounted on this casting.",
    rest: [-0.46, 0.38, 0],
    explode: [-0.85, 0.2, 0],
    service: "Inspect cooling passages for scale buildup if the engine overheats under cruising load. Torque nuts to 18-21 lb-ft.",
    category: "assembly",
  },
  {
    id: "wet-exhaust",
    name: "Wet exhaust mixing elbow",
    short: "Mixing elbow",
    partNumber: "037124",
    qty: "1",
    group: "cooling",
    models: "Marine",
    notes:
      "Injected seawater mixes with hot exhaust gases to cool the exhaust gas down before it travels through fiberglass/rubber exhaust hoses to the waterlock muffler.",
    rest: [-0.55, 0.22, -0.56],
    explode: [-0.95, -0.1, -0.65],
    service: "Pull elbow annually to inspect for carbon encrustation and saltwater corrosion.",
    category: "assembly",
  },
  {
    id: "thermostat-housing",
    name: "Thermostat housing & cover",
    short: "Thermostat",
    partNumber: "037380",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes:
      "Houses the 180°F (82°C) cooling thermostat. Regulates internal freshwater circulation between engine block and heat exchanger.",
    rest: [-0.36, 0.50, 0.42],
    explode: [-0.65, 0.75, 0.55],
    service: "Test thermostat in a pot of hot water with a thermometer if running too cool or overheating.",
    category: "assembly",
  },

  // ===================== FOCUS & FUEL SYSTEM HOSES =====================
  {
    id: "return-hose",
    name: "Hose, injector return to pump (focus part)",
    short: "036868 Return hose",
    partNumber: "036868",
    qty: "1",
    group: "hose",
    models: "20B TWO / 30B THREE",
    highlight: true,
    notes:
      "Official Pub #037115 item 51. Flexible green diesel leak-off hose returning unused bypass fuel from the injector rail back to the injection pump. Critical for pressure balancing. Listed NLA (No Longer Available) on the official factory site — check supersession or use fuel-rated Viton hose of identical ID/OD.",
    rest: [0, 0, 0],
    explode: [0.55, 0.4, 0],
    service: "Secured by two 037163 Keystone clamps. Replace immediately if diesel-soaked, brittle, or swollen.",
    category: "hose",
  },
  {
    id: "fuel-return-hose-2",
    name: "Hose, fuel return line",
    short: "Fuel return 034857",
    partNumber: "034857",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes:
      "Pub #037115 fuel system: Secondary flexible fuel-return line carrying excess fuel back toward the fuel tank / supply circuit.",
    rest: [0, 0, 0],
    explode: [0.5, 0.15, -0.2],
    category: "hose",
  },
  {
    id: "fuel-return-hose-3",
    name: "Hose, auxiliary fuel return",
    short: "Fuel return 037187",
    partNumber: "037187",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Auxiliary return hose section in the 20B/30B fuel circuit connecting the return banjo stack.",
    rest: [0, 0, 0],
    explode: [0.45, 0.1, 0.2],
    category: "hose",
  },
  {
    id: "hose-lift-to-filter",
    name: "Hose, lift pump to fuel filter",
    short: "Hose 038047",
    partNumber: "038047",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Pressurized supply line carrying low-pressure fuel from the 12V electric lift pump to the secondary filter housing.",
    rest: [0, 0, 0],
    explode: [0.55, 0.1, 0.1],
    category: "hose",
  },
  {
    id: "hose-filter-to-inj",
    name: "Hose, filter to injection pump",
    short: "Hose 036865",
    partNumber: "036865",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Clean fuel line connecting the secondary filter outlet directly to the inlet banjo fitting on the injection pump.",
    rest: [0, 0, 0],
    explode: [0.5, 0.15, -0.1],
    category: "hose",
  },
  {
    id: "hose-fuel-supply",
    name: "Hose, fuel supply (tank to Racor)",
    short: "Hose 030025",
    partNumber: "030025",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "USCG Type A1-15 marine diesel fuel supply hose connecting primary Racor filter to engine lift pump.",
    rest: [0, 0, 0],
    explode: [0.6, 0.2, 0.4],
    category: "hose",
  },
  {
    id: "hp-line-1",
    name: "High-pressure injector steel line (cyl 1)",
    short: "HP line 1 (036951)",
    partNumber: "036951",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes:
      "Rigid seamless steel pipe delivering ~2,000 PSI injection pulses from pump delivery valve 1 to injector 1. Do not bend or deform.",
    rest: [0, 0, 0],
    explode: [0.45, 0.35, -0.1],
    category: "hose",
  },
  {
    id: "hp-line-2",
    name: "High-pressure injector steel line (cyl 2)",
    short: "HP line 2 (036952)",
    partNumber: "036952",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Center rigid steel injection line delivering high-pressure fuel pulse to cylinder 2 injector.",
    rest: [0, 0, 0],
    explode: [0.45, 0.35, 0],
    category: "hose",
  },
  {
    id: "hp-line-3",
    name: "High-pressure injector steel line (cyl 3)",
    short: "HP line 3 (036953)",
    partNumber: "036953",
    qty: "1",
    group: "hose",
    models: "30B THREE",
    notes: "Forward rigid steel high-pressure line to cylinder 3 injector (present on 3-cylinder 30B).",
    rest: [0, 0, 0],
    explode: [0.45, 0.35, 0.1],
    category: "hose",
  },
  {
    id: "leak-off-rail",
    name: "Line, injector leak-off bridge rail",
    short: "Leak-off rail 037098",
    partNumber: "037098",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Rigid metal bridge rail spanning all injectors collecting leak-off before the green hose 036868.",
    rest: [0.26, 0.56, 0.04],
    explode: [0.55, 0.85, 0.04],
    category: "hose",
  },

  // ===================== COOLING & SUMP HOSES =====================
  {
    id: "hose-sea-to-heatex",
    name: "Hose, raw-water pump to heat exchanger",
    short: "Hose 037157",
    partNumber: "037157",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Heavy-duty wire-reinforced seawater hose delivering cold saltwater from raw-water pump discharge to heat exchanger tube stack.",
    rest: [0, 0, 0],
    explode: [0.25, 0.5, 0.5],
    category: "hose",
  },
  {
    id: "hose-thermostat-manifold",
    name: "Hose, thermostat to exhaust manifold",
    short: "Hose 037383",
    partNumber: "037383",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Molded freshwater coolant hose bridging the thermostat cover to the water-cooled exhaust manifold jacket.",
    rest: [0, 0, 0],
    explode: [-0.5, 0.4, 0.2],
    category: "hose",
  },
  {
    id: "hose-fw-to-heatex",
    name: "Hose, freshwater circulating pump to heat exchanger",
    short: "Hose 037506",
    partNumber: "037506",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Large bore closed-loop coolant hose returning cooled antifreeze from the exchanger to the internal engine water pump.",
    rest: [0, 0, 0],
    explode: [-0.15, 0.6, 0.35],
    category: "hose",
  },
  {
    id: "hose-flow-ctrl-1",
    name: "Hose, flow control bypass line",
    short: "Hose 036654",
    partNumber: "036654",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Internal temperature control bypass hose ensuring balanced coolant circulation before thermostat fully opens.",
    rest: [0, 0, 0],
    explode: [-0.35, 0.3, 0.4],
    category: "hose",
  },
  {
    id: "hose-flow-ctrl-2",
    name: "Hose, flow control return line",
    short: "Hose 036556",
    partNumber: "036556",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Secondary flow control line balancing water jacket pressures across cylinder block.",
    rest: [0, 0, 0],
    explode: [-0.35, 0.25, 0.35],
    category: "hose",
  },
  {
    id: "hose-sump-drain",
    name: "Hose, oil sump drain line",
    short: "Sump hose 033691",
    partNumber: "033691",
    qty: "1",
    group: "hose",
    models: "20B / 30B",
    notes: "Heavy-duty wire-wound oil drain hose attached to sump banjo bolt 036819. Used for vacuum or gravity oil changes in tight bilges.",
    rest: [0, 0, 0],
    explode: [0.4, -0.3, 0.2],
    service: "Must have brass end plug securely capped to prevent catastrophic oil dumping into the bilge.",
    category: "hose",
  },
  {
    id: "hose-trans-cooler-1",
    name: "Hose, transmission oil cooler supply",
    short: "Trans hose 037154 (1)",
    partNumber: "037154",
    qty: "1",
    group: "hose",
    models: "Marine gear",
    notes: "Seawater cooling line feeding raw water from heat exchanger discharge into the transmission oil cooler.",
    rest: [0, 0, 0],
    explode: [-0.35, -0.15, -0.5],
    category: "hose",
  },
  {
    id: "hose-trans-cooler-2",
    name: "Hose, transmission oil cooler return",
    short: "Trans hose 037154 (2)",
    partNumber: "037154",
    qty: "1",
    group: "hose",
    models: "Marine gear",
    notes: "Return cooling line discharging seawater from the transmission cooler up to the wet exhaust mixing elbow.",
    rest: [0, 0, 0],
    explode: [-0.45, -0.1, -0.45],
    category: "hose",
  },
  {
    id: "hose-coolant-overflow",
    name: "Hose, coolant recovery overflow",
    short: "Overflow tube",
    partNumber: "030030",
    qty: "1",
    group: "hose",
    models: "All",
    notes: "Small clear vinyl tubing connecting heat exchanger radiator neck to the translucent expansion tank bottle.",
    rest: [0, 0, 0],
    explode: [0.5, 0.4, 0.4],
    category: "hose",
  },

  // ===================== HOSE CLAMPS =====================
  {
    id: "clamp-1",
    name: "Keystone clamp (injector return hose top)",
    short: "Keystone clamp 037163",
    partNumber: "037163",
    qty: "1",
    group: "clamp",
    models: "20B / 30B",
    highlight: true,
    notes: "Pub #037115 item 53: Keystone crimp clamp clamping green hose 036868 to the injector leak-off rail. Do not overtighten.",
    rest: [0.26, 0.56, -0.24],
    explode: [0.55, 0.78, -0.24],
    category: "clamp",
  },
  {
    id: "clamp-2",
    name: "Keystone clamp (injector return hose bottom)",
    short: "Keystone clamp 037163",
    partNumber: "037163",
    qty: "1",
    group: "clamp",
    models: "20B / 30B",
    highlight: true,
    notes: "Second 037163 Keystone clamp securing green hose 036868 to the injection pump return barb.",
    rest: [0.44, 0.16, 0.08],
    explode: [0.85, 0.32, 0.12],
    category: "clamp",
  },
  {
    id: "clamp-sea-pump",
    name: "Hose clamp size 16 (sea pump outlet)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless steel worm-gear hose clamp (Size 16, 11/16\" to 1-1/4\") clamping sea pump hose 037157 at pump barb.",
    rest: [0.26, 0.01, 0.72],
    explode: [0.38, 0.25, 0.95],
    category: "clamp",
  },
  {
    id: "clamp-thermo-1",
    name: "Hose clamp size 16 (thermostat cover)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless hose clamp securing hose 037383 at thermostat neck.",
    rest: [-0.36, 0.52, 0.40],
    explode: [-0.62, 0.75, 0.48],
    category: "clamp",
  },
  {
    id: "clamp-thermo-2",
    name: "Hose clamp size 16 (manifold inlet)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Stainless hose clamp securing hose 037383 at the exhaust manifold freshwater jacket.",
    rest: [-0.46, 0.42, 0.18],
    explode: [-0.85, 0.6, 0.22],
    category: "clamp",
  },
  {
    id: "clamp-fw-pump",
    name: "Hose clamp size 16 (freshwater pump)",
    short: "Clamp 011405 (#16)",
    partNumber: "011405",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Secures large circulation hose 037506 to freshwater pump inlet housing.",
    rest: [-0.06, 0.26, 0.66],
    explode: [-0.15, 0.65, 0.95],
    category: "clamp",
  },
  {
    id: "clamp-exchanger-in",
    name: "Hose clamp size 20 (heat exchanger port)",
    short: "Clamp 021878 (#20)",
    partNumber: "021878",
    qty: "1",
    group: "clamp",
    models: "All",
    notes: "Large size 20 stainless hose clamp (3/4\" to 1-3/4\") at heat exchanger raw water inlet.",
    rest: [0.26, 0.72, 0.22],
    explode: [0.4, 0.95, 0.4],
    category: "clamp",
  },
  {
    id: "clamp-small-cooling",
    name: "Hose clamp size 12 (bypass cooling)",
    short: "Clamp 011386 (#12)",
    partNumber: "011386",
    qty: "2",
    group: "clamp",
    models: "All",
    notes: "Size 12 (1/2\" to 1-1/16\") small cooling line clamps for bypass hoses 036654/036556.",
    rest: [-0.28, 0.34, 0.46],
    explode: [-0.45, 0.55, 0.65],
    category: "clamp",
  },
  {
    id: "clamp-fuel-mini",
    name: "Hose clamp mini fuel line",
    short: "Clamp 024906 (Fuel)",
    partNumber: "024906",
    qty: "4",
    group: "clamp",
    models: "All",
    notes: "Precision mini fuel hose clamp providing 360° uniform sealing on supply and return hoses without cutting the rubber jacket.",
    rest: [0.58, -0.06, 0.36],
    explode: [0.95, 0.12, 0.45],
    category: "clamp",
  },

  // ===================== NUTS, WASHERS, STUDS & BANJO HARDWARE =====================
  {
    id: "manifold-studs",
    name: "Studs M8×25 (exhaust manifold to head)",
    short: "M8×25 Studs 015830",
    partNumber: "015830",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "High-tensile heat-resistant metric M8 studs threaded into the cylinder head exhaust ports.",
    rest: [-0.40, 0.38, 0],
    explode: [-0.65, 0.2, 0],
    category: "fastener",
  },
  {
    id: "manifold-washers",
    name: "Washers M8 (flat + spring lock)",
    short: "M8 Washers 031787/786",
    partNumber: "031787 / 031786",
    qty: "12",
    group: "fastener",
    models: "20B / 30B",
    notes: "031787 flat washers + 031786 helical spring lock washers underneath M8 manifold nuts to prevent heat loosening.",
    rest: [-0.49, 0.38, 0],
    explode: [-0.95, 0.2, 0],
    category: "fastener",
  },
  {
    id: "manifold-nuts",
    name: "Nuts M8 (manifold hold-down)",
    short: "M8 Nuts 018242",
    partNumber: "018242",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "M8 metric hex nuts securing the exhaust manifold to the studs. Torque to 18-20 ft-lbs.",
    rest: [-0.52, 0.38, 0],
    explode: [-1.05, 0.2, 0],
    category: "fastener",
  },
  {
    id: "valve-cover-bolts",
    name: "Capscrews M6 with M6 flat & lock washers",
    short: "M6 Bolts 018804 / 031784",
    partNumber: "018804 / 031784 / 031783",
    qty: "4",
    group: "fastener",
    models: "20B / 30B",
    notes: "M6 capscrews with washer stacks securing the valve rocker cover. Overtightening distorts the flange and causes oil leaks.",
    rest: [0, 0.55, 0],
    explode: [0, 1.15, 0],
    service: "Torque gently to 6-8 ft-lbs (8-10 N·m) with new rubber isolator grommets.",
    category: "fastener",
  },
  {
    id: "banjo-return-stack",
    name: "Washers, banjo crush copper (fuel return stack)",
    short: "Banjo washer 037105 ×2",
    partNumber: "037105",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    highlight: true,
    notes: "Soft copper crush sealing washers on the fuel-return banjo fitting. Single-use only — once compressed they work-harden and will weep diesel if reused.",
    rest: [0.44, 0.16, 0.08],
    explode: [0.82, 0.25, 0.14],
    service: "CRITICAL: Always install fresh copper crush washers on every banjo bolt service to prevent fuel mist leaks.",
    category: "fastener",
  },
  {
    id: "banjo-bleed-stack",
    name: "Washer, banjo crush (fuel bleed stack)",
    short: "Bleed washer 037104",
    partNumber: "037104",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "Copper sealing washer on the injection pump air-bleed banjo screw.",
    rest: [0.44, 0.24, 0.04],
    explode: [0.88, 0.35, 0.08],
    category: "fastener",
  },
  {
    id: "banjo-bolt-bleed",
    name: "Banjo bolt, air bleed valve",
    short: "Bleed bolt 037110",
    partNumber: "037110",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hollow cross-drilled banjo bolt used to bleed trapped air from the injection pump gallery after filter changes.",
    rest: [0.44, 0.26, 0.04],
    explode: [0.95, 0.4, 0.08],
    service: "Loosen 1 turn while operating electric lift pump until clear fuel flows without bubbles, then snug down.",
    category: "fastener",
  },
  {
    id: "banjo-bolt-fuel",
    name: "Banjo bolt, fuel pump inlet/return",
    short: "Banjo bolt 037111 / 016988",
    partNumber: "037111 / 016988",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "Precision machined hollow bolt with cross-drilled fuel metering orifice for injection pump supply.",
    rest: [0.46, 0.06, -0.04],
    explode: [0.92, 0.15, -0.06],
    category: "fastener",
  },
  {
    id: "banjo-washer-m8",
    name: "Banjo crush washer M8",
    short: "M8 Banjo washer 030289",
    partNumber: "030289",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "M8 copper sealing ring for small diesel gallery banjo ports.",
    rest: [0.42, 0.12, 0.14],
    explode: [0.82, 0.2, 0.2],
    category: "fastener",
  },
  {
    id: "banjo-washer-m14",
    name: "Banjo crush washer M14",
    short: "M14 Banjo washer 030291",
    partNumber: "030291",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "M14 heavy copper sealing ring for main fuel feed banjo connections.",
    rest: [0.46, 0.06, -0.04],
    explode: [0.88, 0.14, -0.05],
    category: "fastener",
  },
  {
    id: "banjo-cooling-m16",
    name: "Banjo washer M16 (cooling circuit)",
    short: "M16 Banjo washer 037162",
    partNumber: "037162",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "Large M16 copper sealing washer for cooling jacket temperature senders and bypass ports.",
    rest: [-0.34, 0.44, 0.38],
    explode: [-0.65, 0.7, 0.52],
    category: "fastener",
  },
  {
    id: "banjo-sump-washers",
    name: "Banjo crush washers ×2 (oil sump drain)",
    short: "Sump washer 036493 ×2",
    partNumber: "036493",
    qty: "2",
    group: "fastener",
    models: "20B / 30B",
    notes: "Dual copper crush washers sealing both sides of the remote oil drain banjo fitting at the bottom of the oil pan.",
    rest: [0.28, -0.38, 0.1],
    explode: [0.55, -0.65, 0.18],
    category: "fastener",
  },
  {
    id: "banjo-sump-bolt",
    name: "Banjo bolt (oil sump drain valve)",
    short: "Sump banjo bolt 036819",
    partNumber: "036819",
    qty: "1",
    group: "fastener",
    models: "20B / 30B",
    notes: "High-strength hollow banjo bolt securing oil drain hose 033691 to oil pan bottom port.",
    rest: [0.28, -0.38, 0.1],
    explode: [0.65, -0.65, 0.18],
    category: "fastener",
  },
  {
    id: "injector-nuts",
    name: "Nuts, injector high-pressure line flare & hold-down",
    short: "Injector nuts 036921",
    partNumber: "036921",
    qty: "6",
    group: "fastener",
    models: "20B / 30B",
    notes: "Hardened flare tube nuts and hold-down clamp nuts. Torque to 22-25 ft-lbs.",
    rest: [0.25, 0.52, 0.04],
    explode: [0.6, 0.88, 0.04],
    category: "fastener",
  },
  {
    id: "injector-gaskets",
    name: "Gaskets, injector nozzle copper heat shields & leak-off",
    short: "Injector gaskets 036922",
    partNumber: "036922",
    qty: "3",
    group: "fastener",
    models: "20B / 30B",
    notes: "Solid copper combustion heat-shield washers placed beneath injector nozzle tips. Prevents compression blowby.",
    rest: [0.25, 0.44, 0.04],
    explode: [0.5, 0.65, 0.04],
    category: "fastener",
  },
  {
    id: "engine-mount-nuts",
    name: "Nuts M12 self-locking (vibration isolator mounts)",
    short: "M12 Locknut 037353",
    partNumber: "037353",
    qty: "4",
    group: "fastener",
    models: "All",
    notes: "Heavy nylon-insert self-locking M12 nuts securing engine foot brackets to rubber vibration isolators.",
    rest: [0, -0.22, 0],
    explode: [0, -0.5, 0],
    category: "fastener",
  },
  {
    id: "alt-adjust-bolt",
    name: "Alternator adjuster bolt M10 with flat & lock washer",
    short: "M10 Bolt 015887 / 031789",
    partNumber: "015887 / 031789 / 019262",
    qty: "1",
    group: "fastener",
    models: "All",
    notes: "M10 slotted bracket adjustment bolt used to tension the V-belt.",
    rest: [0.44, 0.26, 0.60],
    explode: [0.88, 0.36, 0.82],
    category: "fastener",
  },
  {
    id: "prop-castle-nut",
    name: "Slotted brass castle nut, cotter pin & drive key",
    short: "Castle nut 037388",
    partNumber: "037388",
    qty: "1",
    group: "fastener",
    models: "Marine shaft",
    notes: "Heavy marine brass slotted castle nut and bronze cotter pin locking the propeller onto the shaft taper.",
    rest: [0, -0.04, -2.18],
    explode: [0, -0.1, -3.00],
    category: "fastener",
  },

  // ===================== FUEL SYSTEM MAJOR ASSEMBLIES =====================
  {
    id: "injection-pump",
    name: "Fuel injection pump assembly",
    short: "Injection pump",
    partNumber: "037102 (20B) / 037103 (30B)",
    qty: "1",
    group: "fuel",
    models: "037102 = 20B TWO; 037103 = 30B THREE",
    notes:
      "Bosch-type precision mechanical inline injection pump driven by engine camshaft. Generates timed, metered high-pressure fuel pulses to each injector. Internal governor regulates idle and cruising RPM.",
    rest: [0.44, 0.02, 0.04],
    explode: [0.85, 0, 0.08],
    service: "Injection timing is shim-adjusted to ±1° BTDC (17°-19° BTDC). Never disassemble without a dedicated diesel injection test bench.",
    category: "assembly",
  },
  {
    id: "injector-1",
    name: "Diesel fuel injector (cyl 1)",
    short: "Injector 1 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Complete injector assembly (nozzle holder, calibrated pressure spring, multi-hole atomizing nozzle tip). Pop pressure set to 1,920–2,060 PSI.",
    rest: [0.25, 0.48, -0.24],
    explode: [0.55, 0.8, -0.24],
    service: "Pop-test spray pattern and check chatter sound if cylinder is misfiring or smoking black.",
    category: "assembly",
  },
  {
    id: "injector-2",
    name: "Diesel fuel injector (cyl 2)",
    short: "Injector 2 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Center injector assembly on 30B THREE (forward injector on 20B TWO).",
    rest: [0.25, 0.48, 0.04],
    explode: [0.55, 0.84, 0.04],
    category: "assembly",
  },
  {
    id: "injector-3",
    name: "Diesel fuel injector (cyl 3)",
    short: "Injector 3 (037091)",
    partNumber: "037091",
    qty: "1",
    group: "fuel",
    models: "30B THREE",
    notes: "Forward cylinder 3 injector assembly on 3-cylinder models.",
    rest: [0.25, 0.48, 0.24],
    explode: [0.55, 0.8, 0.24],
    category: "assembly",
  },
  {
    id: "glow-plugs",
    name: "Glow plugs & busbar harness",
    short: "Glow plugs 036930",
    partNumber: "036930",
    qty: "3",
    group: "electrical",
    models: "20B / 30B",
    notes: "12V electric pre-heat elements threaded into pre-combustion chambers. Energized for 10-15 seconds before cold starting.",
    rest: [0.22, 0.42, 0.02],
    explode: [0.48, 0.68, 0.02],
    service: "Check resistance with multimeter (approx 0.8 to 1.2 ohms each). Open circuit = dead plug.",
    category: "assembly",
  },
  {
    id: "racor",
    name: "Primary fuel filter / water separator (aftermarket)",
    short: "Racor R15T / 500FG",
    partNumber: "Racor R15T / R15S",
    qty: "1",
    group: "fuel",
    models: "Aftermarket visible in photos",
    notes:
      "Visible in boat photographs on bulkhead. 10-micron spin-on separator with clear sediment bowl and brass water drain petcock. First line of defense against contaminated marine fuel.",
    rest: [0.78, 0.38, 0.36],
    explode: [1.18, 0.42, 0.48],
    service: "Check clear bowl before every startup. Drain accumulated water immediately.",
    category: "assembly",
  },
  {
    id: "stock-filter",
    name: "Stock secondary fuel filter assembly",
    short: "Secondary filter 030210",
    partNumber: "030210 (Element 030200)",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Original Westerbeke engine-mounted 2-micron fine filter. Purifies diesel before entering injection pump.",
    rest: [0.52, 0.18, -0.22],
    explode: [0.92, 0.22, -0.26],
    service: "Replace element 030200 every 200 hours or annually. Always bleed air after element change.",
    category: "assembly",
  },
  {
    id: "lift-pump",
    name: "Fuel lift pump 12V DC",
    short: "Lift pump 039275",
    partNumber: "039275",
    qty: "1",
    group: "fuel",
    models: "20B / 30B",
    notes: "Solid-state 12V electric pulse lift pump drawing fuel from tank and pressurizing secondary filter. Gives rapid clicking sound during pre-heat / prime.",
    rest: [0.58, -0.12, 0.36],
    explode: [0.98, -0.18, 0.48],
    service: "If engine sputters or dies under load, listen for pump clicking or check inlet mesh screen.",
    category: "assembly",
  },

  // ===================== COOLING & ELECTRICAL =====================
  {
    id: "heat-exchanger",
    name: "Tubular heat exchanger assembly",
    short: "Heat exchanger",
    partNumber: "037130",
    qty: "1",
    group: "cooling",
    models: "Marine 20B/30B",
    notes:
      "Copper-nickel cupronickel tube stack inside an aluminum/bronze casing. Seawater flows through internal tubes while engine freshwater circulates across outer shell.",
    rest: [0.02, 0.72, 0.12],
    explode: [0, 1.15, 0.15],
    service: "Inspect sacrificial zinc anode (011885) monthly. Replace when 50% eroded.",
    category: "assembly",
  },
  {
    id: "zinc-anode",
    name: "Sacrificial zinc anode plug (pencil zinc)",
    short: "Zinc anode 011885",
    partNumber: "011885",
    qty: "1",
    group: "cooling",
    models: "All marine",
    notes: "1/4\" NPT brass plug with sacrificial zinc rod threaded into heat exchanger bottom. Protects heat exchanger from galvanic corrosion.",
    rest: [0.02, 0.64, 0.12],
    explode: [0.02, 0.95, 0.4],
    service: "Check every 30-60 days. If zinc is completely gone, seawater will eat the copper-nickel core!",
    category: "assembly",
  },
  {
    id: "raw-water-pump",
    name: "Raw-water seawater pump",
    short: "Sea pump 037140",
    partNumber: "037140 (Impeller 036618)",
    qty: "1",
    group: "cooling",
    models: "Marine",
    notes: "Bronze body pump with flexible neoprene impeller, gear-driven off front gear case. Pumps seawater through heat exchanger and wet exhaust.",
    rest: [0.26, -0.06, 0.70],
    explode: [0.45, -0.05, 1.15],
    service: "Carry spare impeller 036618 and paper gasket on board. Never run dry!",
    category: "assembly",
  },
  {
    id: "freshwater-pump",
    name: "Freshwater circulating water pump",
    short: "Circulating pump",
    partNumber: "037145",
    qty: "1",
    group: "cooling",
    models: "20B / 30B",
    notes: "Belt-driven internal centrifugal coolant pump circulating antifreeze through the block and cylinder head.",
    rest: [-0.06, 0.30, 0.66],
    explode: [-0.15, 0.45, 1.05],
    category: "assembly",
  },
  {
    id: "coolant-bottle",
    name: "Translucent coolant recovery expansion bottle",
    short: "Coolant bottle",
    partNumber: "030040",
    qty: "1",
    group: "cooling",
    models: "All",
    notes: "Visible in boat photos mounted next to Racor. Holds expanded coolant and allows visual inspection of antifreeze level and clarity.",
    rest: [0.82, 0.08, 0.52],
    explode: [1.22, 0.02, 0.65],
    category: "assembly",
  },
  {
    id: "alternator",
    name: "Marine 12V 55A alternator",
    short: "Alternator 037170",
    partNumber: "037170",
    qty: "1",
    group: "electrical",
    models: "12V marine isolated ground",
    notes: "Heavy-duty marine alternator with internal regulator and spark-arrested screen for marine safety compliance.",
    rest: [0.44, 0.16, 0.62],
    explode: [0.92, 0.14, 0.88],
    category: "assembly",
  },
  {
    id: "alt-bracket",
    name: "Alternator mounting & adjusting arm bracket",
    short: "Alt bracket 037172",
    partNumber: "037172",
    qty: "1",
    group: "electrical",
    models: "20B / 30B",
    notes: "Cast bracket bolting alternator to cylinder head with slotted adjustment arm.",
    rest: [0.38, 0.18, 0.52],
    explode: [0.78, 0.24, 0.75],
    category: "assembly",
  },
  {
    id: "starter",
    name: "12V reduction gear starter motor",
    short: "Starter motor 037180",
    partNumber: "037180",
    qty: "1",
    group: "electrical",
    models: "12V 1.2kW",
    notes: "High-torque reduction starter with integrated solenoid. Engages flywheel ring gear to crank the diesel.",
    rest: [-0.40, -0.08, -0.52],
    explode: [-0.92, -0.14, -0.56],
    service: "Check heavy gauge battery cable terminals for corrosion if clicking without cranking.",
    category: "assembly",
  },

  // ===================== DRIVE, TRANSMISSION, SHAFT & PROPELLER =====================
  {
    id: "pulley",
    name: "Crankshaft damper drive pulley",
    short: "Crank pulley",
    partNumber: "036912",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Machined harmonic drive pulley keyed to front crankshaft snout. Drives freshwater pump and alternator V-belt.",
    rest: [0, 0.02, 0.72],
    explode: [0, 0, 1.15],
    category: "assembly",
  },
  {
    id: "belt",
    name: "V-belt drive (crank to pump & alternator)",
    short: "Drive belt 037168",
    partNumber: "037168",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "High-temperature marine grade V-belt. Tension should allow 1/2\" deflection under moderate thumb pressure.",
    rest: [0, 0, 0],
    explode: [0.15, 0.15, 1.15],
    service: "Carry a spare drive belt on board. A thrown belt stops raw water cooling immediately!",
    category: "assembly",
  },
  {
    id: "flywheel-housing",
    name: "Flywheel bell housing",
    short: "Bell housing",
    partNumber: "037185",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Cast aluminum bell housing enclosing flywheel and damper plate; mounts marine transmission to cylinder block.",
    rest: [0, -0.02, -0.66],
    explode: [0, 0, -0.55],
    cutaway: true,
    category: "assembly",
  },
  {
    id: "flywheel",
    name: "Flywheel & starter ring gear",
    short: "Flywheel",
    partNumber: "036915",
    qty: "1",
    group: "drive",
    models: "20B / 30B",
    notes: "Heavy cast iron flywheel providing rotational inertia and smooth idling. Coupled to transmission torsional damper plate.",
    rest: [0, -0.02, -0.66],
    explode: [0, 0, -1.05],
    category: "assembly",
  },
  {
    id: "transmission",
    name: "Marine transmission gearbox (Hurth / ZF)",
    short: "Transmission (ZF/Hurth)",
    partNumber: "HBW-50 / ZF10M",
    qty: "1",
    group: "drive",
    models: "Mechanical marine gear (2.05:1 / 2.72:1)",
    notes: "Helical-gear marine reduction gearbox with multi-disc clutch pack. Bolted flush to flywheel bell housing; delivers power to propeller shaft.",
    rest: [0, -0.04, -0.98],
    explode: [0, -0.1, -1.65],
    service: "Check ATF fluid level with dipstick unscrewed. Clean fluid is bright translucent red.",
    category: "assembly",
  },
  {
    id: "trans-cooler",
    name: "Transmission oil heat exchanger cooler",
    short: "Trans cooler 037150",
    partNumber: "037150",
    qty: "1",
    group: "drive",
    models: "Marine",
    notes: "In-line tube oil cooler mounted on port bracket, cooling marine transmission oil with raw seawater.",
    rest: [-0.34, -0.04, -0.92],
    explode: [-0.65, -0.08, -1.35],
    category: "assembly",
  },
  {
    id: "shift-linkage",
    name: "Transmission shift lever & cable bracket",
    short: "Shift lever",
    partNumber: "037190",
    qty: "1",
    group: "controls",
    models: "All",
    notes: "External actuator lever mounted on selector pivot boss; connects cockpit Morse control cable to gearbox selector spool.",
    rest: [-0.18, 0.10, -0.95],
    explode: [-0.60, 0.20, -1.45],
    category: "assembly",
  },
  {
    id: "throttle",
    name: "Throttle speed control lever & governor linkage",
    short: "Throttle linkage",
    partNumber: "037195",
    qty: "1",
    group: "controls",
    models: "20B / 30B",
    notes: "Precision ball-joint linkage rod visible in photographs. Connects helm throttle cable to injection pump governor rack.",
    rest: [0.46, 0.26, 0.22],
    explode: [0.82, 0.44, 0.35],
    service: "Lightly lube ball joints annually. Ensure free return spring action back to idle stop.",
    category: "assembly",
  },
  {
    id: "driveshaft-coupling",
    name: "Flexible shaft coupling & isolator disc",
    short: "Shaft coupling 037360",
    partNumber: "037360 (Drivesaver)",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "High-strength polyurethane flexible vibration damping disc isolating the gearbox from propeller shaft thrust and vibration.",
    rest: [0, -0.04, -1.24],
    explode: [0, -0.1, -1.80],
    category: "assembly",
  },
  {
    id: "shaft-coupling-hub",
    name: "Split shaft coupling hub with clamp bolts",
    short: "Coupling hub 037362",
    partNumber: "037362",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "Heavy precision machined steel split coupling with clamping bolts and keyway locking onto the stainless driveshaft.",
    rest: [0, -0.04, -1.32],
    explode: [0, -0.1, -2.00],
    category: "assembly",
  },
  {
    id: "prop-driveshaft",
    name: "Stainless steel propeller driveshaft (1\" Aquamet)",
    short: "Driveshaft 037365",
    partNumber: "037365",
    qty: "1",
    group: "drive",
    models: "1\" Aquamet 17/22",
    notes: "Precision-ground marine stainless steel propeller shaft transmitting rotational torque from gearbox to propeller.",
    rest: [0, -0.04, -1.75],
    explode: [0, -0.1, -2.40],
    category: "assembly",
  },
  {
    id: "shaft-seal-stuffing",
    name: "Bronze marine stuffing box / shaft seal packing gland",
    short: "Shaft seal 037370",
    partNumber: "037370 (PSS / Packing)",
    qty: "1",
    group: "drive",
    models: "Marine 1\" shaft",
    notes: "Cast bronze stuffing box gland with packing nut and flax seals (or PSS dripless face seal) preventing bilge flooding.",
    rest: [0, -0.04, -1.48],
    explode: [0, -0.1, -2.15],
    service: "Traditional packing should drip 2-3 drops/min while underway to lubricate flax packing.",
    category: "assembly",
  },
  {
    id: "stern-tube-hose",
    name: "Heavy-duty stern tube hose with T-bolt clamps",
    short: "Stern hose 037372",
    partNumber: "037372",
    qty: "1",
    group: "hose",
    models: "Marine 1-3/4\" ID",
    notes: "5-ply wire-reinforced marine silicone/rubber hose bridging shaft seal stuffing box to the boat stern tube with dual 316SS T-bolt clamps.",
    rest: [0, -0.04, -1.58],
    explode: [0, -0.1, -2.25],
    category: "hose",
  },
  {
    id: "shaft-zinc-anode",
    name: "Sacrificial zinc collar anode (shaft zinc)",
    short: "Shaft zinc 037378",
    partNumber: "037378",
    qty: "1",
    group: "drive",
    models: "1\" shaft",
    notes: "Streamlined split zinc collar clamped around propeller shaft forward of strut to protect shaft and propeller from galvanic electrolysis.",
    rest: [0, -0.04, -1.88],
    explode: [0, -0.1, -2.55],
    service: "Replace whenever 50% wasted or at every seasonal haulout.",
    category: "assembly",
  },
  {
    id: "propeller",
    name: "3-Blade bronze marine propeller (14RH10 cupped)",
    short: "Propeller 037385",
    partNumber: "037385",
    qty: "1",
    group: "drive",
    models: "14RH10 / 15RH11 (1\" bore)",
    notes: "Manganese bronze 3-blade cupped marine propeller optimized for auxiliary sailboat cruising thrust at 3,600 engine RPM (approx 1,750 shaft RPM).",
    rest: [0, -0.04, -2.10],
    explode: [0, -0.1, -2.85],
    category: "assembly",
  },

  // ===================== LUBRICATION & SERVICE =====================
  {
    id: "oil-filter",
    name: "Full-flow spin-on lube oil filter",
    short: "Oil filter 036918",
    partNumber: "036918",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "High-efficiency spin-on oil filter element. Traps soot, carbon, and wear metals.",
    rest: [0.48, -0.14, -0.38],
    explode: [0.90, -0.22, -0.45],
    service: "Change with every 100-hour oil change. Pre-fill with fresh 15W-40 oil before threading on.",
    category: "assembly",
  },
  {
    id: "oil-dipstick",
    name: "Oil dipstick & guide tube",
    short: "Dipstick 036925",
    partNumber: "036925",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "Graduated dipstick with yellow/red pull handle for checking engine oil level.",
    rest: [0.42, 0.1, -0.28],
    explode: [0.85, 0.25, -0.38],
    category: "assembly",
  },
  {
    id: "oil-fill-cap",
    name: "Oil filler cap & O-ring seal",
    short: "Oil cap 036928",
    partNumber: "036928",
    qty: "1",
    group: "lubrication",
    models: "20B / 30B",
    notes: "Threaded filler cap on top of valve rocker cover.",
    rest: [0, 0.62, 0.38],
    explode: [0, 1.25, 0.38],
    category: "assembly",
  },

  // ===================== RUNNING GEAR INTERNALS =====================
  {
    id: "crankshaft",
    name: "Forged steel crankshaft",
    short: "Crankshaft",
    partNumber: "036935",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Heavy precision-balanced forged steel crankshaft with integral counterweights and induction-hardened journals.",
    rest: [0, -0.16, 0],
    explode: [0, -0.65, 0],
    category: "internal",
  },
  {
    id: "piston-1",
    name: "Piston & ring pack (cyl 1)",
    short: "Piston 1",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Aluminum alloy piston with combustion bowl in crown, dual compression rings, and 3-piece oil control ring.",
    rest: [0, 0.08, -0.24],
    explode: [0, 0.35, -0.45],
    category: "internal",
  },
  {
    id: "piston-2",
    name: "Piston & ring pack (cyl 2)",
    short: "Piston 2",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Center cylinder piston on 30B THREE.",
    rest: [0, 0.08, 0.04],
    explode: [0, 0.4, 0.04],
    category: "internal",
  },
  {
    id: "piston-3",
    name: "Piston & ring pack (cyl 3)",
    short: "Piston 3",
    partNumber: "036940",
    qty: "1",
    group: "internals",
    models: "30B THREE",
    notes: "Forward cylinder piston on 30B THREE.",
    rest: [0, 0.08, 0.24],
    explode: [0, 0.35, 0.45],
    category: "internal",
  },
  {
    id: "rod-1",
    name: "Connecting rod & bearing cap (cyl 1)",
    short: "Rod 1",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Forged I-beam connecting rod with precision tri-metal bronze-lead rod bearings.",
    rest: [0, -0.04, -0.24],
    explode: [0.15, -0.35, -0.45],
    category: "internal",
  },
  {
    id: "rod-2",
    name: "Connecting rod & bearing cap (cyl 2)",
    short: "Rod 2",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Center connecting rod assembly.",
    rest: [0, -0.04, 0.04],
    explode: [0.15, -0.4, 0.04],
    category: "internal",
  },
  {
    id: "rod-3",
    name: "Connecting rod & bearing cap (cyl 3)",
    short: "Rod 3",
    partNumber: "036945",
    qty: "1",
    group: "internals",
    models: "30B THREE",
    notes: "Forward connecting rod assembly.",
    rest: [0, -0.04, 0.24],
    explode: [0.15, -0.35, 0.45],
    category: "internal",
  },
  {
    id: "camshaft",
    name: "Camshaft & valve lifters",
    short: "Camshaft",
    partNumber: "036950",
    qty: "1",
    group: "internals",
    models: "20B / 30B",
    notes: "Gear-driven camshaft operating intake/exhaust valves via pushrods and rocker arms at 1/2 engine speed.",
    rest: [0, 0.22, 0],
    explode: [0, 0.55, 0],
    category: "internal",
  },
];

export const PARTS_BY_ID: Record<string, EnginePart> = Object.fromEntries(
  PARTS.map((p) => [p.id, p]),
);

export const STRIP_ORDER: string[] = [
  // 1. External Accessories & Hoses
  "belt",
  "pulley",
  "alternator",
  "alt-bracket",
  "alt-adjust-bolt",
  "coolant-bottle",
  "hose-coolant-overflow",
  "racor",
  "hose-fuel-supply",
  // 2. Focus Green Hose & Return Clamps
  "clamp-1",
  "clamp-2",
  "return-hose",
  "fuel-return-hose-2",
  "fuel-return-hose-3",
  "clamp-fuel-mini",
  // 3. High Pressure Lines & Fuel System
  "hp-line-1",
  "hp-line-2",
  "hp-line-3",
  "leak-off-rail",
  "injector-nuts",
  "injector-gaskets",
  "injector-1",
  "injector-2",
  "injector-3",
  "glow-plugs",
  "throttle",
  "banjo-return-stack",
  "banjo-bleed-stack",
  "banjo-bolt-bleed",
  "banjo-bolt-fuel",
  "banjo-washer-m8",
  "banjo-washer-m14",
  "hose-filter-to-inj",
  "hose-lift-to-filter",
  "lift-pump",
  "stock-filter",
  "injection-pump",
  // 4. Cooling & Exhaust Group
  "clamp-sea-pump",
  "hose-sea-to-heatex",
  "clamp-thermo-1",
  "clamp-thermo-2",
  "hose-thermostat-manifold",
  "clamp-fw-pump",
  "hose-fw-to-heatex",
  "clamp-exchanger-in",
  "clamp-small-cooling",
  "hose-flow-ctrl-1",
  "hose-flow-ctrl-2",
  "zinc-anode",
  "heat-exchanger",
  "raw-water-pump",
  "freshwater-pump",
  "thermostat-housing",
  "wet-exhaust",
  "manifold-nuts",
  "manifold-washers",
  "manifold-studs",
  "manifold",
  "banjo-cooling-m16",
  // 5. Valve Train & Engine Tops
  "valve-cover-bolts",
  "oil-fill-cap",
  "valve-cover",
  "oil-filter",
  "oil-dipstick",
  "starter",
  // 6. Sump & Mounts
  "hose-sump-drain",
  "banjo-sump-washers",
  "banjo-sump-bolt",
  "engine-mount-nuts",
  // 7. Drive, Transmission, Prop Shaft & Propeller
  "prop-castle-nut",
  "propeller",
  "shaft-zinc-anode",
  "shaft-seal-stuffing",
  "stern-tube-hose",
  "prop-driveshaft",
  "shaft-coupling-hub",
  "driveshaft-coupling",
  "shift-linkage",
  "hose-trans-cooler-1",
  "hose-trans-cooler-2",
  "trans-cooler",
  "transmission",
  "flywheel",
  "flywheel-housing",
  // 8. Engine Block & Internals
  "head",
  "oil-pan",
  "camshaft",
  "piston-1",
  "piston-2",
  "piston-3",
  "rod-1",
  "rod-2",
  "rod-3",
  "crankshaft",
  "block",
];

export const MANUALS = [
  {
    label: "Parts list #037115",
    href: "https://www.westerbeke.com/parts%20manual/37115_rev2_12c_20b_30b_parts_list.pdf",
  },
  {
    label: "Tech manual #037600",
    href: "https://www.westerbeke.com/technical%20manual/37600_12c_20b_30b_technical_manual.pdf",
  },
  {
    label: "Westerbeke official",
    href: "https://www.westerbeke.com/",
  },
];
